import type { Issue, OpsApi } from "@team-hq/api-contract";

const DEMO: Issue[] = [
  {
    id: "demo_1",
    title: "行銷卡 hover 狀態",
    projectSlug: "marketing",
    assigneeRole: "frontend",
    status: "blocked",
    blockedReason: "等 UI 規格確認",
    source: "manual",
    sourceRef: null,
    updatedAt: "2026-09-20T10:00:00.000Z",
    updatedBy: "mei",
  },
  {
    id: "demo_2",
    title: "iframe 容器 RWD",
    projectSlug: "iframe",
    assigneeRole: "frontend",
    status: "doing",
    blockedReason: null,
    source: "manual",
    sourceRef: null,
    updatedAt: "2026-09-20T11:00:00.000Z",
    updatedBy: "frontend",
  },
  {
    id: "demo_3",
    title: "輪播 API 契約",
    projectSlug: "carousel",
    assigneeRole: "backend",
    status: "doing",
    blockedReason: null,
    source: "bot_report",
    sourceRef: "bot:carousel-1",
    updatedAt: "2026-09-20T12:00:00.000Z",
    updatedBy: "backend",
  },
  {
    id: "demo_4",
    title: "試穿 flow QA 清單",
    projectSlug: "try-on",
    assigneeRole: "qa",
    status: "todo",
    blockedReason: null,
    source: "manual",
    sourceRef: null,
    updatedAt: "2026-09-20T13:00:00.000Z",
    updatedBy: "mei",
  },
  {
    id: "demo_5",
    title: "LLM modal 無障礙",
    projectSlug: "llm-chat",
    assigneeRole: "uiux",
    status: "todo",
    blockedReason: null,
    source: "manual",
    sourceRef: null,
    updatedAt: "2026-09-20T14:00:00.000Z",
    updatedBy: "mei",
  },
  {
    id: "demo_6",
    title: "Team HQ Filter State shell",
    projectSlug: "team-ops",
    assigneeRole: "cto",
    status: "doing",
    blockedReason: null,
    source: "manual",
    sourceRef: null,
    updatedAt: "2026-09-21T01:00:00.000Z",
    updatedBy: "cto",
  },
  {
    id: "demo_7",
    title: "CI 管線骨架",
    projectSlug: "team-ops",
    assigneeRole: "devops",
    status: "blocked",
    blockedReason: "等待 secrets 決策",
    source: "bot_report",
    sourceRef: "bot:ci-1",
    updatedAt: "2026-09-21T02:00:00.000Z",
    updatedBy: "devops",
  },
  {
    id: "demo_8",
    title: "PRD 對齊 checklist",
    projectSlug: "team-ops",
    assigneeRole: "pm",
    status: "done",
    blockedReason: null,
    source: "manual",
    sourceRef: null,
    updatedAt: "2026-09-19T09:00:00.000Z",
    updatedBy: "mei",
  },
];

export function seedDemoIssues(api: OpsApi): void {
  for (const issue of DEMO) {
    api.seedIssue(issue);
  }
}
